### PR TITLE
Add Ruby 2.3.0 support

### PR DESCRIPTION
**Pull request by milkcocoa**
Set ruby-2.3.0 as default

### CODE REVIEW

**Comment by eitoball** [comment]
:+1:

**Comment by takuyan** [comment]
:+1:

**Comment by sue445** [comment]
:+1:

**Comment by brunoocasali** [comment]
:+1: related with this issue #17 LOL (I had not seen this pull request before)

**Comment by olliebennett** [comment]
Just for information, the Docker-based stack now supports Ruby 2.3.0 since [DockerHub](https://hub.docker.com/_/ruby/) was updated earlier today.

This might be the opportunity we've been looking for to switch from the Classic stack (eg. `box: wercker/rvm` in your `wercker.yml`) to the Docker stack (eg. `box: ruby:2.3`).

Either way, it would be good to have the latest Ruby supported here too.

**Comment by hatchan** [comment]
Thanks @milkcocoa. And good point @olliebennett :+1:

**Comment by brunoocasali** [comment]
Hey guys, anyone here use `nokogiri` as a dependency?  I've many problems when build :/

**Comment by olliebennett** [comment]
I don't believe that's related to this issue (or Wercker at all), @brunoocasali .

FWIW, yes - we use `nokogiri` and have no problems with this new (or any) version of the `wercker/rvm` box, and we're not doing anything clever or customised. Nokogiri is notoriously difficult to build; I suggest trying a few re-builds on Wercker and see if it resolves itself.

As a side note, I noticed a new step called `fix-nokogiri` in the new Wercker (Docker) stack - it might be worth you investigating whether updating to Docker solves your problem. Good luck!

**Comment by brunoocasali** [comment]
Thanks @olliebennett :+1:

**Comment by sue445** [comment]
@brunoocasali @olliebennett I also encountered the same problem with `box: ruby:2.3` (using Docker-based style) too.

error log : https://gist.github.com/sue445/8dee5f1311c72b44450e

`bundle install` was successful after I added `bundle config build.nokogiri --use-system-libraries`

# wercker.yml
```yaml
box: ruby:2.3
build:
    steps:
        - script:
            name: bundle config
            code: bundle config build.nokogiri --use-system-libraries

        - bundle-install
```

**Comment by brunoocasali** [comment]
@sue445 Very Thanks! It worked! :wine_glass: to you or :beer: :P

**Pull request merged**
